### 모듈(라이브러리) 사용하기
import numpy as np

- numpy 모듈(라이브러리)를 import하고 앞으로 np라는 이름으로 부른다.


numpy.ndarray 클래스
- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)이 부여되어 있다
- ndarray를 줄여서 array로 표현한다.

In [5]:
# numpy 라이브러리 import 하기
# 앞으로 np라는 이름으로 부르기
import numpy as np

In [6]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [7]:
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [8]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [9]:
# 연산을 진행하면 각 요소끼리 연산을 진행
arr+arr1

array([ 2,  4,  6,  8, 10])

In [10]:
# 리스트
# [1,2,3], [4,5,6] 각 요소의 값을 더한다

In [11]:
list1=[1,2,3]
list2=[4,5,6]
list3=[]
for i in range(3):
    list3.append(list1[i] + list2[i])
print(list3)

[5, 7, 9]


In [12]:
# 2차원 array 생성하기
arr2 = np.array([[1,2,3], [4,5,6]])
arr2
arr2[0]+arr2[1]

array([5, 7, 9])

In [13]:
# array의 크기 확인하기
# shape
arr2.shape

(2, 3)

In [14]:
# array의 전체 요소 개수 확인하기
#size
arr2.size

6

In [15]:
# array의 타입 확인하기
# dtype
arr2.dtype

dtype('int32')

In [16]:
# array의 차원 확인하기
# ndim
arr2.ndim

2

In [17]:
# 3차원의 array만들고 배열의 크기, 차원, 전체 요소개수 확인
arr3 = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# 배열의 크기 : shape
# 배열의 차원 : ndim
# 배열의 개수 : size

print("배열의 크기 : {}".format(arr3.shape))
print(f"배열의 차원 : {arr3.ndim}")
print("배열의 개수 : %d"%(arr3.size))
print()
print('배열의 크기 : ',arr3.shape)
print('배열의 차원 : ',arr3.ndim)
print('배열의 개수 : ',arr3.size)

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8

배열의 크기 :  (2, 2, 2)
배열의 차원 :  3
배열의 개수 :  8


In [19]:
# 배열 생성하기
# 0값으로 생성하기
# zeros(배열의 크기)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# 1값으로 생성하기
#ones()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# 지정해서 생성하기
# full(배열의 크기, 채워넣을 값)
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [22]:
# 연속되는 숫자로 배열 생성하기
# arange(시작하는 수, 끝나는 수+1, 간격이되는 수)
# 시작하는 수 기본 값 : 0
# 간격이되는 수 기본값 : 1
np.arange(0,50,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
np.arange(1,50,10)

array([ 1, 11, 21, 31, 41])

In [24]:
oo = np.arange(1,50,10)
print(oo)

[ 1 11 21 31 41]


In [25]:
# 1부터 50까지 1씩 커지는 배열 만들기
# np linspace(시작하는 수, 끝나는 수, 등분할 값)
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [26]:
# 랜덤값으로 배열 생성하기
# np.random.rand(배열의 크기)
# 0 ~ 1 사이의 값을 가지는 배열을 생성
np.random.rand(2,3)

array([[0.20201591, 0.63786201, 0.11472329],
       [0.80030906, 0.27352598, 0.1191581 ]])

In [27]:
# 원하는 범위에서 랜덤값 생성
# np.random.randint(시작수, 끝수+1,size = 배열의 크기)
np.random.randint(2,10,size = (3,2))

array([[4, 3],
       [9, 3],
       [2, 9]])

In [28]:
# 2부터 10까지의 랜덤한 실수값으로 이루어진 (5,4) 크기의 배열 생성
# np.random.rand, np.random.randint 사용
a = np.random.rand(5,4)
print(a+np.random.randint(2,10,size=(5,4)))

[[4.2351882  7.45589507 8.69272421 2.92097807]
 [9.68934321 3.8245574  4.99592162 9.18664761]
 [5.68267791 7.69995609 9.02039362 3.76556267]
 [8.32708526 9.73785552 7.21666138 2.17976074]
 [5.50830331 5.24708504 7.52176657 2.47364395]]


In [29]:
# 5부터 6까지 랜덤한 실수
5+np.random.rand(5,4)

array([[5.79789116, 5.47441639, 5.23412793, 5.60448468],
       [5.5627017 , 5.21297212, 5.88795023, 5.64515311],
       [5.68762882, 5.91441258, 5.55725182, 5.09364539],
       [5.69932365, 5.21947618, 5.62730199, 5.34863743],
       [5.21919681, 5.94765903, 5.7521764 , 5.62280464]])

In [30]:
# 타입 변경하기
# 배열.astype(변경할 타입)

In [31]:
b=a+np.random.randint(2,10,size=(5,4))
b.astype("int")
print(b)


[[6.2351882  2.45589507 5.69272421 3.92097807]
 [6.68934321 8.8245574  9.99592162 6.18664761]
 [6.68267791 3.69995609 8.02039362 6.76556267]
 [5.32708526 9.73785552 7.21666138 6.17976074]
 [8.50830331 9.24708504 7.52176657 6.47364395]]


### 배열의 생성 ###


In [32]:
### 배열의 기능 ###

In [33]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# 인덱싱
# []
# 2차원에서 0번째 출력
arr[0]

array([1, 2, 3])

In [35]:
print(arr[0,1])
print(arr[0][1])

2
2


In [36]:
# 슬라이싱

In [37]:
# 0 ~ 9까지의 값이 담긴 배열 생성
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# 3부터 7까지의 값 출력
print(arr1[3:8])

[3 4 5 6 7]


In [39]:
arr2 = np.arange(50)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [40]:
# arr2를 (5,10)으로 재 배열하기
# reshape
# 바뀌기 전과 후의 데이터 수가 똑같아야함
# 출력을 진행하고 저장은 진행되지 않음
arr2 = arr2.reshape(5,10) # 변수에 담아주어야 저장이 됨
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
# 2차원 슬라이싱
# 시작수 : 끝수 + 1
# : 끝수 + 1 = 처음부터 끝수까지
# 시작수 : = 시작수부터 끝까지
# : 처음부터 끝까지
arr2[:2,1:4]

array([[ 1,  2,  3],
       [11, 12, 13]])

In [42]:
print(arr2[:5,:1]) # arr2[:,0]
print(arr2[:4,:5])

[[ 0]
 [10]
 [20]
 [30]
 [40]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [43]:
# 파일 불러오기
data=np.loadtxt("height_weight.txt", delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [44]:
bmi = data[1:,:] / ((data[:1,:]/100)**2)
bmi

array([[21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
        20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998]])

In [45]:
bmi2 = data[1]/((data[0]/100)**2)
bmi2

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [46]:
# Boolean 인덱싱
# True는 출력하고 False는 출력하지 않음
# 인덱싱을 진행할때 값의 개수와 동일한 수의 불리언 데이터 필요
# 원하는 조건에 맞는 값을 출력하는 방법
arr3 = np.array([10,20,15,30])
arr3

array([10, 20, 15, 30])

In [47]:
bol=np.array([True,False,True,False])
bol

array([ True, False,  True, False])

In [48]:
arr3[bol]

array([10, 15])

In [49]:
# 17 미만인  값 출력
arr3[arr3 < 17]

array([10, 15])

In [50]:
# arr3에서 20인 값만 출력
print(arr3==20)
arr3[arr3==20]

[False  True False False]


array([20])

In [51]:
# numpy에서 사용하는 연산 함수

In [52]:
# 1 ~ 9까지의 랜덤한 정수가 담긴 2,5 크기의 배열 생성
arr = np.random.randint(1,10,size=(2,5))
arr

array([[6, 6, 3, 8, 4],
       [1, 4, 2, 3, 2]])

In [99]:
# 배열 안에 있는 값 더하기
# np.sum(배열값)
np.sum(arr, axis = 0)

array([ 7, 10,  5, 11,  6])

In [54]:
# 배열 안에 있는 값의 평균
# np.mean(배열값)
np.mean(arr, axis=1)

array([5.4, 2.4])

## 영화 평점 데이터 분석하기

In [55]:
# 데이터 타입 변경
# dtype
data = np.loadtxt('ratings.txt', delimiter="::",dtype = 'int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [56]:
# 전체 평점 평균 구하기
np.mean(data[:,2])

3.581564453029317

In [90]:
# 각 사용자별 평점 평균 구하기
# 리스트에 [사용자, 사용자의 평점평균] 저장하기
# 1번 사용자의 평점 평균 구하기
num1=data[(data[:,0]==1)] # 전체 정보에서 id값이 1인 값만 출력
np.mean(num1[:,2])
num2=[]
for i in range(1,6041):
    num = data[(data[:,0]==i)]
    num2.append([i, np.mean(num[:,2])])
num2

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [98]:
# 각 사용자별 평균 평점이 4점 이상인 사용자 구하기
user_list4 = []
for i in range(6040):
    if num2[i][1] >= 4:
        user_list4.append(num2[i])

user_list4


[[1, 4.188679245283019],
 [4, 4.190476190476191],
 [7, 4.32258064516129],
 [10, 4.114713216957606],
 [17, 4.075829383886256],
 [20, 4.083333333333333],
 [27, 4.171428571428572],
 [36, 4.199430199430199],
 [43, 4.125],
 [46, 4.219512195121951],
 [53, 4.2368421052631575],
 [54, 4.025],
 [55, 4.12],
 [64, 4.148148148148148],
 [65, 4.347107438016529],
 [67, 4.296875],
 [69, 4.153846153846154],
 [74, 4.046511627906977],
 [75, 4.005714285714285],
 [76, 4.172413793103448],
 [81, 4.4186046511627906],
 [82, 4.016949152542373],
 [86, 4.3125],
 [88, 4.147058823529412],
 [91, 4.704545454545454],
 [97, 4.474025974025974],
 [101, 4.679245283018868],
 [103, 4.052173913043478],
 [105, 4.295081967213115],
 [106, 4.0212765957446805],
 [109, 4.0],
 [112, 4.183333333333334],
 [121, 4.416666666666667],
 [124, 4.173913043478261],
 [125, 4.098591549295775],
 [126, 4.0],
 [128, 4.363636363636363],
 [129, 4.025316455696203],
 [130, 4.311111111111111],
 [138, 4.492307692307692],
 [150, 4.021551724137931],
 [152